# Generated by Django 4.0.3 on 2022-04-28 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter song genre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Enter a short description', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lyrics', models.TextField(help_text='Enter a song text')),
                ('chords', models.TextField(help_text='Enter the list of chords')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this song', to='catalog.genre')),
                ('singer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.singer')),
            ],
        ),
    ]
